language: node_js

node_js:
    - 8

branches:
    only:
    - master

install:
- npm install
- npm install -g codecov

script:
- npm run test
- CODECOV_TOKEN="9deeda0f-dbfb-4e20-9550-90870bebb895" codecov